### ISSUE TITLE
Code glitchy and freezing

### ISSUE THREAD

**Issue by StuffnThingz** [Montana-Media-Arts/120_CreativeCoding_Fall2017#64] opened 2017-12-11 18:34 UTC
My code is kind of working but glitchy and it freezes sometimes. Just trying to get all the balls to disappear when they intersect. Can anyone point out what I did wrong? I'm guessing it has something to do with the splice in the array?

(https://github.com/StuffnThingz/120-work/blob/master/hw-12/sketch.js)

(https://github.com/StuffnThingz/120-work/blob/master/hw-12/bubbles.js)

(https://stuffnthingz.github.io/120-work/hw-12/)

**Comment by madisonflaget** [comment] 2017-12-11 21:55
I think the issue is that the array that's involved with the splice needs to work through itself backwards. [Week 12: Interacting with objects](https://montana-media-arts.github.io/creative-coding-1/modules/week-12/objects-interacting/) Part 3 explains why

**Comment by JonSwallow** [comment] 2017-12-11 21:57
@StuffnThingz I ran your code and it does work really well until it freezes. I had the same problem but it was glitchy for me in the same area of code but my problem was in how many of a given object I had. I just kept running it changing it running it again until I got rid of the error. Anyway the only thing I see in your code that even remotely looks different is in the move function.
Here is what you have. 
```
  move() {
    this.x += this.delta_x * this.scale_x;
    this.y += this.delta_y * this.scale_y;

    if (this.x >= width || this.x <= 0) {
        this.delta_x = -1 * this.delta_x;
    }
    if (this.y >= height || this.y <= 0) {
        this.delta_y = -1 * this.delta_y;
  }
}
``` 
Here is what I did it may be worth assigning a function just for the change of motion. 
```
  this.motion = function() {
    this.x += this.deltaX;
      this.y += this.deltaY;
  }
  
 
  
 
  this.reversal = function() {
      if(this.x + this.r >= width || this.x - this.r <= 0) {
        this.deltaX *= -1.9;
      }
      if(this.y + this.r >= height || this.y - this.r <= 0) {
          this.deltaY *= -1.9;
     }
```
Try doing that and see if it helps. Ignore the - 1.9 mine is not a constant use what you have just assign it to a separate function. Not sure about the extra * this. delta_X and Y but if it works rock on.

**Comment by StuffnThingz** [comment] 2017-12-12 02:21
Thanks @madisonflaget  and @JonSwallow !  Reversing the array seemed to help a bit, but it's still freezing sometimes.  You think it has something to do with the intersect function? When I check for errors in the html console it says "Cannot read property 'intersects' of undefined"

**Comment by StuffnThingz** [comment] 2017-12-12 02:52
Here's what my sketch.js looks like now. Reversing the second index made the balls move faster like how I wanted them to, but it's still freezing sometimes.

(https://github.com/StuffnThingz/120-work/blob/master/practice%20folder/sketch.js)

**Closed** 2018-01-19 18:24 UTC
